name: Create zip files

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UUID: 'block-caribou-36@lxylxy123456.ercli.dev'
    strategy:
      matrix:
        version:
          - '3.36.3'
          - '40.0'

    steps:
    - uses: actions/checkout@v2
    - name: check
      run: grep -A999 -B999 ${{ env.UUID }} ${{ matrix.version }}/metadata.json
    - name: zip
      run: zip -j ${{ matrix.version }}.zip ${{ matrix.version }}/*
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.version }}.zip
        path: ${{ matrix.version }}.zip
    - name: create_release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: auto-release-${{ github.sha }}
        release_name: Auto Release ${{ github.sha }}
        body: |
          Automatically created by GitHub Actions
        draft: false
        prerelease: false
    - name: release
      if: ${{ (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master' && github.event_name == 'push') }}
      id: release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ matrix.version }}.zip
        asset_name: ${{ matrix.version }}.zip
        asset_content_type: application/zip

